name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        env
        echo $DOCKER_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
        docker build -t ghcr.io/guru-ntt/demo:latest --file ./sample-packages/docker/Dockerfile .
        docker push ghcr.io/guru-ntt/demo:latest
